CREATE TABLE MOGESDOC.TIPO_USUARIO (
  ID          int(10) NOT NULL AUTO_INCREMENT, 
  NOMBRE      varchar(32) NOT NULL, 
  DESCRIPCION varchar(100) NOT NULL, 
  ESTADO      varchar(2) NOT NULL, 
  CONSTRAINT PK_TIPO_USUARIO 
    PRIMARY KEY (ID), 
  UNIQUE INDEX (ID));
CREATE TABLE MOGESDOC.USUARIO (
  USUARIO        numeric(13, 0) NOT NULL, 
  CLAVE          varchar(255) NOT NULL, 
  ESTADO         varchar(2) NOT NULL, 
  FECHA_CREACION date NOT NULL, 
  OBSERVACION    varchar(100), 
  TIPO_USUARIO   int(10) NOT NULL, 
  PERFIL         int(10) NOT NULL, 
  CONSTRAINT PK_USUARIO 
    PRIMARY KEY (USUARIO), 
  UNIQUE INDEX (USUARIO));
CREATE TABLE MOGESDOC.PERFIL (
  ID             int(10) NOT NULL AUTO_INCREMENT, 
  NOMBRE         varchar(32), 
  ESTADO         varchar(2) NOT NULL, 
  FECHA_CREACION date NOT NULL, 
  CONSTRAINT PK_PERFIL 
    PRIMARY KEY (ID), 
  UNIQUE INDEX (ID));
CREATE TABLE MOGESDOC.PERMISO (
  ID             int(10) NOT NULL AUTO_INCREMENT, 
  NOMBRE         varchar(32) NOT NULL, 
  ESTADO         varchar(2) NOT NULL, 
  DESCRIPCION    varchar(100) NOT NULL, 
  FECHA_CREACION date NOT NULL, 
  CONSTRAINT PK_PERMISO 
    PRIMARY KEY (ID), 
  UNIQUE INDEX (ID));
CREATE TABLE MOGESDOC.PERFIL_PERMISO (
  ID      int(10) NOT NULL AUTO_INCREMENT, 
  PERFIL  int(10) NOT NULL, 
  PERMISO int(10) NOT NULL, 
  CONSTRAINT PK_PERFIL_PERMISO 
    PRIMARY KEY (ID), 
  UNIQUE INDEX (ID));
CREATE TABLE MOGESDOC.TIPO_DOCUMENTO (
  ID             int(10) NOT NULL AUTO_INCREMENT, 
  NOMBRE         varchar(32) NOT NULL, 
  ESTADO         varchar(2) NOT NULL, 
  DESCRIPCION    varchar(100), 
  FECHA_CREACION date NOT NULL, 
  CONSTRAINT PK_TIPO_DOCUMENTO 
    PRIMARY KEY (ID), 
  UNIQUE INDEX (ID));
CREATE TABLE MOGESDOC.DOCUMENTO (
  ID             int(10) NOT NULL AUTO_INCREMENT, 
  NOMBRE         varchar(128) NOT NULL, 
  EXTENSION      varchar(4) NOT NULL, 
  FECHA_CREACION date NOT NULL, 
  AUTOR          varchar(32) NOT NULL, 
  RUTA           varchar(255) NOT NULL, 
  TIPO_DOCUMENTO int(10) NOT NULL, 
  PREFIJO        int(10) NOT NULL, 
  CONSTRAINT PK_DOCUMENTO 
    PRIMARY KEY (ID), 
  UNIQUE INDEX (ID));
CREATE TABLE MOGESDOC.BITACORA_DOCUMENTO (
  ID             int(10) NOT NULL AUTO_INCREMENT, 
  USUARIO        numeric(13, 0) NOT NULL, 
  DOCUMENTO      int(10) NOT NULL, 
  FECHA_REGISTRO date NOT NULL, 
  TIPO_ACCION    int(4) NOT NULL, 
  DESCRIPCION    varchar(128) NOT NULL, 
  CONSTRAINT PK_BITACORA_DOCUMENTO 
    PRIMARY KEY (ID), 
  UNIQUE INDEX (ID));
CREATE TABLE MOGESDOC.ORGANIZACION (
  ID               int(10) NOT NULL AUTO_INCREMENT, 
  CODIGO           varchar(4) NOT NULL, 
  NOMBRE           varchar(150) NOT NULL, 
  ESTADO           varchar(2) NOT NULL, 
  URL              varchar(64), 
  TELEFONO         int(10), 
  PREFIJO_TELEFONO int(4), 
  LOGOTIPO         blob NOT NULL, 
  CONSTRAINT PK_ORGANIZACION 
    PRIMARY KEY (ID), 
  UNIQUE INDEX (ID), 
  UNIQUE INDEX (CODIGO));
CREATE TABLE MOGESDOC.AREA (
  ID           int(10) NOT NULL AUTO_INCREMENT, 
  NOMBRE       varchar(128) NOT NULL, 
  CODIGO       varchar(4) NOT NULL UNIQUE, 
  ORGANIZACION int(10) NOT NULL, 
  CONSTRAINT PK_AREA 
    PRIMARY KEY (ID), 
  UNIQUE INDEX (ID));
CREATE TABLE MOGESDOC.UNIDAD (
  ID          int(10) NOT NULL AUTO_INCREMENT, 
  CODIGO      varchar(4) NOT NULL, 
  NOMBRE      varchar(128) NOT NULL, 
  ESTADO      varchar(2) NOT NULL, 
  DESCRIPCION varchar(128), 
  AREA        int(10) NOT NULL, 
  CONSTRAINT PK_UNIDAD 
    PRIMARY KEY (ID), 
  UNIQUE INDEX (ID));
CREATE TABLE MOGESDOC.AGENCIA (
  ID        int(10) NOT NULL AUTO_INCREMENT, 
  CODIGO    varchar(4) NOT NULL, 
  NOMBRE    varchar(128) NOT NULL, 
  ESTADO    varchar(2) NOT NULL, 
  UNIDAD    int(10) NOT NULL, 
  MUNICIPIO int(10) NOT NULL, 
  CONSTRAINT PK_AGENCIA 
    PRIMARY KEY (ID), 
  UNIQUE INDEX (ID));
CREATE TABLE MOGESDOC.PAIS (
  ID     int(10) NOT NULL AUTO_INCREMENT, 
  CODIGO varchar(6) NOT NULL UNIQUE, 
  NOMBRE varchar(128) NOT NULL, 
  ESTADO varchar(2) NOT NULL, 
  CONSTRAINT PK_PAIS 
    PRIMARY KEY (ID), 
  UNIQUE INDEX (ID));
CREATE TABLE MOGESDOC.DEPARTAMENTO (
  ID     int(10) NOT NULL AUTO_INCREMENT, 
  CODIGO varchar(4) NOT NULL, 
  NOMBRE varchar(128) NOT NULL, 
  ESTADO varchar(2) NOT NULL, 
  PAIS   int(10) NOT NULL, 
  CONSTRAINT PK_DEPARTAMENTO 
    PRIMARY KEY (ID), 
  UNIQUE INDEX (ID));
CREATE TABLE MOGESDOC.MUNIICIPIO (
  ID           int(10) NOT NULL AUTO_INCREMENT, 
  CODIGO       varchar(4) NOT NULL, 
  NOMBRE       varchar(128) NOT NULL, 
  ESTADO       varchar(2) NOT NULL, 
  DEPARTAMENTO int(10) NOT NULL, 
  CONSTRAINT PK_MUNICIPIO 
    PRIMARY KEY (ID), 
  UNIQUE INDEX (ID));
CREATE TABLE MOGESDOC.USUARIO_AGENCIA (
  ID                 int(10) NOT NULL AUTO_INCREMENT, 
  USUARIO            numeric(13, 0) NOT NULL, 
  AGENCIA            int(10) NOT NULL, 
  ESTADO             varchar(2) NOT NULL, 
  FECHA_CREACION     date NOT NULL, 
  FECHA_MODIFICACION date,
  CONSTRAINT PK_USUARIO_AGENCIA 
    PRIMARY KEY (ID), 
  UNIQUE INDEX (ID));
CREATE TABLE MOGESDOC.CORRESPONDENCIA (
  ID                   int(10) NOT NULL AUTO_INCREMENT, 
  FECHA_CREACION       date NOT NULL, 
  TIPO_CORRESPONDENCIA int(10) NOT NULL, 
  DOCUMENTO            int(10) NOT NULL, 
  USUARIO_AGENCIA      int(10) NOT NULL, 
  PRIORIDAD            int(4) NOT NULL, 
  DESTINATARIO         varchar(128) NOT NULL, 
  REMITENTE            varchar(128) NOT NULL, 
  TIPO_MENSAJERIA      int(10) NOT NULL, 
  ESTADO               varchar(2) NOT NULL, 
  CONSTRAINT PK_CORRESPONDENCIA 
    PRIMARY KEY (ID), 
  UNIQUE INDEX (ID));
CREATE TABLE MOGESDOC.TIPO_CORRESPONDENCIA (
  ID          int(10) NOT NULL AUTO_INCREMENT, 
  NOMBRE      varchar(128) NOT NULL, 
  ESTADO      varchar(2) NOT NULL, 
  DESCRIPCION varchar(128), 
  CONSTRAINT PK_TIPO_CORRESPONDENCIA 
    PRIMARY KEY (ID), 
  UNIQUE INDEX (ID));
CREATE TABLE MOGESDOC.TIPO_PREFIJO (
  ID     int(10) NOT NULL AUTO_INCREMENT, 
  NOMBRE varchar(32) NOT NULL, 
  ESTADO varchar(2) NOT NULL, 
  CONSTRAINT PK_TIPO_PREFIJO 
    PRIMARY KEY (ID), 
  UNIQUE INDEX (ID));
CREATE TABLE MOGESDOC.PREFIJO_DOCUMENTO (
  ID           int(10) NOT NULL AUTO_INCREMENT, 
  AREA         varchar(10) NOT NULL, 
  UNIDAD       varchar(10) NOT NULL, 
  AGENCIA      varchar(10) NOT NULL, 
  TIPO_PREFIJO int(10) NOT NULL, 
  CONSTRAINT PK_PREFIJO_DOCUMENTO 
    PRIMARY KEY (ID), 
  UNIQUE INDEX (ID));
CREATE TABLE MOGESDOC.DETALLE_CORRESPONDENCIA (
  ID                 int(10) NOT NULL AUTO_INCREMENT, 
  CORRESPONDENCIA    int(10) NOT NULL, 
  FECHA_MODIFICACION date NOT NULL, 
  ESTADO_ANTERIOR    varchar(2) NOT NULL, 
  CONSTRAINT PK_DETALLE_CORRESPONDENCIA 
    PRIMARY KEY (ID), 
  UNIQUE INDEX (ID));
CREATE TABLE MOGESDOC.TIPO_MENSAJERIA (
  ID          int(10) NOT NULL AUTO_INCREMENT, 
  NOMBRE      varchar(128) NOT NULL, 
  DESCRIPCION varchar(128) NOT NULL, 
  CONSTRAINT PK_TIPO_MENSAJERIA 
    PRIMARY KEY (ID), 
  UNIQUE INDEX (ID));
ALTER TABLE MOGESDOC.USUARIO ADD CONSTRAINT REL_TIPO_USUARIO FOREIGN KEY (TIPO_USUARIO) REFERENCES MOGESDOC.TIPO_USUARIO (ID) ON UPDATE Cascade ON DELETE Cascade;
ALTER TABLE MOGESDOC.PERFIL_PERMISO ADD CONSTRAINT REL_PERFIL FOREIGN KEY (PERFIL) REFERENCES MOGESDOC.PERFIL (ID) ON UPDATE Cascade ON DELETE Cascade;
ALTER TABLE MOGESDOC.PERFIL_PERMISO ADD CONSTRAINT REL_PERMISO FOREIGN KEY (PERMISO) REFERENCES MOGESDOC.PERMISO (ID) ON UPDATE Cascade ON DELETE Cascade;
ALTER TABLE MOGESDOC.USUARIO ADD CONSTRAINT REL_USUARIO_PERFIL FOREIGN KEY (PERFIL) REFERENCES MOGESDOC.PERFIL (ID) ON UPDATE Cascade ON DELETE Cascade;
ALTER TABLE MOGESDOC.DOCUMENTO ADD CONSTRAINT REL_TIPO_DOCUMENTO FOREIGN KEY (TIPO_DOCUMENTO) REFERENCES MOGESDOC.TIPO_DOCUMENTO (ID) ON UPDATE Cascade ON DELETE Cascade;
ALTER TABLE MOGESDOC.BITACORA_DOCUMENTO ADD CONSTRAINT REL_DOCUMENTO_BITACORA FOREIGN KEY (DOCUMENTO) REFERENCES MOGESDOC.DOCUMENTO (ID) ON UPDATE No action ON DELETE No action;
ALTER TABLE MOGESDOC.BITACORA_DOCUMENTO ADD CONSTRAINT REL_USUARIO_BITACORA FOREIGN KEY (USUARIO) REFERENCES MOGESDOC.USUARIO (USUARIO) ON UPDATE No action ON DELETE No action;
ALTER TABLE MOGESDOC.AREA ADD CONSTRAINT REL_ORGANIZACION FOREIGN KEY (ORGANIZACION) REFERENCES MOGESDOC.ORGANIZACION (ID) ON UPDATE Cascade ON DELETE Cascade;
ALTER TABLE MOGESDOC.UNIDAD ADD CONSTRAINT REL_AREA FOREIGN KEY (AREA) REFERENCES MOGESDOC.AREA (ID) ON UPDATE Cascade ON DELETE Cascade;
ALTER TABLE MOGESDOC.AGENCIA ADD CONSTRAINT REL_UNIDAD FOREIGN KEY (UNIDAD) REFERENCES MOGESDOC.UNIDAD (ID) ON UPDATE Cascade ON DELETE Cascade;
ALTER TABLE MOGESDOC.DEPARTAMENTO ADD CONSTRAINT REL_PAIS FOREIGN KEY (PAIS) REFERENCES MOGESDOC.PAIS (ID) ON UPDATE Cascade ON DELETE Cascade;
ALTER TABLE MOGESDOC.MUNIICIPIO ADD CONSTRAINT REL_DEPARTAMENTO FOREIGN KEY (DEPARTAMENTO) REFERENCES MOGESDOC.DEPARTAMENTO (ID) ON UPDATE Cascade ON DELETE Cascade;
ALTER TABLE MOGESDOC.AGENCIA ADD CONSTRAINT REL_MUNICIPIO_AGENCIA FOREIGN KEY (MUNICIPIO) REFERENCES MOGESDOC.MUNIICIPIO (ID) ON UPDATE No action ON DELETE No action;
ALTER TABLE MOGESDOC.USUARIO_AGENCIA ADD CONSTRAINT REL_USUARIO_AGENCIA FOREIGN KEY (USUARIO) REFERENCES MOGESDOC.USUARIO (USUARIO) ON UPDATE Cascade ON DELETE Cascade;
ALTER TABLE MOGESDOC.USUARIO_AGENCIA ADD CONSTRAINT REL_AGENCIA_USUARIO FOREIGN KEY (AGENCIA) REFERENCES MOGESDOC.AGENCIA (ID) ON UPDATE Cascade ON DELETE Cascade;
ALTER TABLE MOGESDOC.CORRESPONDENCIA ADD CONSTRAINT REL_TIPO_CORRESPONDENCIA FOREIGN KEY (TIPO_CORRESPONDENCIA) REFERENCES MOGESDOC.TIPO_CORRESPONDENCIA (ID) ON UPDATE Cascade ON DELETE Cascade;
ALTER TABLE MOGESDOC.CORRESPONDENCIA ADD CONSTRAINT REL_DOCUMENTO_CORRESPONDENCIA FOREIGN KEY (DOCUMENTO) REFERENCES MOGESDOC.DOCUMENTO (ID) ON UPDATE No action ON DELETE No action;
ALTER TABLE MOGESDOC.CORRESPONDENCIA ADD CONSTRAINT REL_USUARIO_CORRESPONDENCIA FOREIGN KEY (USUARIO_AGENCIA) REFERENCES MOGESDOC.USUARIO_AGENCIA (ID) ON UPDATE Cascade ON DELETE Cascade;
ALTER TABLE MOGESDOC.PREFIJO_DOCUMENTO ADD CONSTRAINT REL_TIPO_PREFIJO FOREIGN KEY (TIPO_PREFIJO) REFERENCES MOGESDOC.TIPO_PREFIJO (ID) ON UPDATE Cascade ON DELETE Cascade;
ALTER TABLE MOGESDOC.CORRESPONDENCIA ADD CONSTRAINT REL_TIPO_MENSAJERIA FOREIGN KEY (TIPO_MENSAJERIA) REFERENCES MOGESDOC.TIPO_MENSAJERIA (ID) ON UPDATE Cascade ON DELETE Cascade;
ALTER TABLE MOGESDOC.DETALLE_CORRESPONDENCIA ADD CONSTRAINT REL_CORRESPONDENCIA_DETALLE FOREIGN KEY (CORRESPONDENCIA) REFERENCES MOGESDOC.CORRESPONDENCIA (ID) ON UPDATE Cascade ON DELETE Cascade;
ALTER TABLE MOGESDOC.DOCUMENTO ADD CONSTRAINT REL_PREFIJO_DOCUMENTO FOREIGN KEY (PREFIJO) REFERENCES MOGESDOC.PREFIJO_DOCUMENTO (ID) ON UPDATE Cascade ON DELETE Cascade;
